import sys, os, time, threading, queue
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from config import AUDIO_DIR, DEFAULT_LANGUAGE, ACK_TIMEOUT_SEC, FAST_ACK_COUNT

passed = 0
failed = 0

def check(name, condition, expected=None, got=None):
    global passed, failed
    if condition:
        print(f"  {name}")
        passed += 1
    else:
        print(f"  {name}")
        if expected is not None:
            print(f"     Expected: {expected}")
            print(f"     Got:      {got}")
        failed += 1


# TEST 1 — Audio directory exists

print("\n" + "="*55)
print("TEST 1 — Audio directory structure")
print("="*55)

check("assets/audio/ directory exists",
      os.path.isdir(AUDIO_DIR),
      "directory exists", AUDIO_DIR)


# TEST 2 — Audio files exist (generated by generate_audio.py)
# we can replace that file in real world deployement with pre-generated MP3 files, but for testing we will generate them on the fly.

print("\n" + "="*55)
print("TEST 2 — Required audio files present")
print("="*55)

from config import (AUDIO_L1_BEEP, AUDIO_L2_HINDI, AUDIO_L2_MARATHI,
                    AUDIO_L3_HINDI, AUDIO_L3_MARATHI, AUDIO_CAMERA_CHECK)

required_files = [
    (AUDIO_L1_BEEP,       "Level 1 beep"),
    (AUDIO_L2_HINDI,      "Level 2 Hindi voice"),
    (AUDIO_L2_MARATHI,    "Level 2 Marathi voice"),
    (AUDIO_L3_HINDI,      "Level 3 Hindi voice"),
    (AUDIO_L3_MARATHI,    "Level 3 Marathi voice"),
    (AUDIO_CAMERA_CHECK,  "Camera check alert"),
]

audio_files_ready = True
for fname, desc in required_files:
    fpath   = os.path.join(AUDIO_DIR, fname)
    exists  = os.path.exists(fpath)
    size_ok = os.path.getsize(fpath) > 1000 if exists else False
    check(f"{desc} ({fname}) exists and is >1KB",
          exists and size_ok,
          "file exists and >1KB",
          f"exists={exists}, size={os.path.getsize(fpath) if exists else 0}B")
    if not (exists and size_ok):
        audio_files_ready = False

if not audio_files_ready:
    print("\n    Audio files missing. Run to generate them:")
    print("     uv run scripts/generate_audio.py")
    print("  The alert engine will fall back to console output until files exist.")


# TEST 3 — AlertEngine imports correctly

print("\n" + "="*55)
print("TEST 3 — AlertEngine imports and initializes")
print("="*55)

try:
    from core.alert_engine import AlertEngine
    check("AlertEngine imports without error", True)

    session_state = {
        "session_id":    "TEST",
        "alert_level":   0,
        "alert_active":  False,
        "threshold_raised": 0.0,
    }
    session_lock   = threading.Lock()
    alert_q        = queue.Queue(maxsize=3)
    db_q           = queue.Queue(maxsize=50)
    ack_event      = threading.Event()
    shutdown_event = threading.Event()

    engine = AlertEngine(
        alert_q, db_q, ack_event, shutdown_event,
        session_state, session_lock, language="marathi"
    )
    check("AlertEngine instantiates without error", True)
    check("AlertEngine language set to marathi",
          engine.language == "marathi", "marathi", engine.language)
    check("AlertEngine threshold_raised starts at 0",
          engine.threshold_raised == 0.0, 0.0, engine.threshold_raised)

except Exception as e:
    check("AlertEngine imports and initializes", False, "no error", str(e))


# TEST 4 — Audio file selection logic


print("TEST 4 — Audio file selection per level + language")


try:
    from core.alert_engine import AlertEngine
    from config import (AUDIO_L1_BEEP, AUDIO_L2_MARATHI, AUDIO_L2_HINDI,
                        AUDIO_L3_MARATHI, AUDIO_L3_HINDI)

    session_state_m = {"session_id": "T", "alert_level": 0,
                       "alert_active": False, "threshold_raised": 0.0}
    eng_m = AlertEngine(queue.Queue(), queue.Queue(), threading.Event(),
                        threading.Event(), session_state_m,
                        threading.Lock(), language="marathi")
    eng_h = AlertEngine(queue.Queue(), queue.Queue(), threading.Event(),
                        threading.Event(), session_state_m,
                        threading.Lock(), language="hindi")

    check("Level 1 → l1_beep regardless of language",
          eng_m._get_audio_file(1) == AUDIO_L1_BEEP,
          AUDIO_L1_BEEP, eng_m._get_audio_file(1))
    check("Level 2 + Marathi → l2_marathi.mp3",
          eng_m._get_audio_file(2) == AUDIO_L2_MARATHI,
          AUDIO_L2_MARATHI, eng_m._get_audio_file(2))
    check("Level 2 + Hindi → l2_hindi.mp3",
          eng_h._get_audio_file(2) == AUDIO_L2_HINDI,
          AUDIO_L2_HINDI, eng_h._get_audio_file(2))
    check("Level 3 + Marathi → l3_marathi.mp3",
          eng_m._get_audio_file(3) == AUDIO_L3_MARATHI,
          AUDIO_L3_MARATHI, eng_m._get_audio_file(3))
    check("Level 3 + Hindi → l3_hindi.mp3",
          eng_h._get_audio_file(3) == AUDIO_L3_HINDI,
          AUDIO_L3_HINDI, eng_h._get_audio_file(3))

except Exception as e:
    check("Audio file selection logic", False, "no error", str(e))


# TEST 5 — Fast-ack threshold learning with safety ceiling

print("\n" + "="*55)
print("TEST 5 — Fast-ack learning: threshold raises with safety ceiling")
print("="*55)

from config import FAST_ACK_RAISE, FAST_ACK_MAX_RAISE

try:
    session_state_t = {"session_id": "T", "alert_level": 0,
                       "alert_active": False, "threshold_raised": 0.0,
                       "ack_times": []}
    eng_t = AlertEngine(
        queue.Queue(), queue.Queue(), threading.Event(),
        threading.Event(), session_state_t, threading.Lock()
    )

    # Simulate fast acks
    eng_t.threshold_raised = 0.0

    # First raise
    eng_t.threshold_raised = 0.0
    eng_t._raise_threshold()
    check(f"First raise: threshold = {FAST_ACK_RAISE}",
          abs(eng_t.threshold_raised - FAST_ACK_RAISE) < 0.001,
          FAST_ACK_RAISE, eng_t.threshold_raised)

    # Second raise
    eng_t._raise_threshold()
    check(f"Second raise: threshold = {FAST_ACK_RAISE*2:.2f}",
          abs(eng_t.threshold_raised - FAST_ACK_RAISE*2) < 0.001,
          FAST_ACK_RAISE*2, eng_t.threshold_raised)

    # Push to ceiling
    eng_t.threshold_raised = FAST_ACK_MAX_RAISE - 0.001
    eng_t._raise_threshold()
    check(f"Ceiling enforced: threshold never exceeds {FAST_ACK_MAX_RAISE}",
          eng_t.threshold_raised <= FAST_ACK_MAX_RAISE,
          f"<= {FAST_ACK_MAX_RAISE}", eng_t.threshold_raised)

    # At ceiling — raise has no effect
    before = eng_t.threshold_raised
    eng_t.threshold_raised = FAST_ACK_MAX_RAISE
    eng_t._raise_threshold()
    check("At ceiling: further raise has no effect",
          eng_t.threshold_raised == FAST_ACK_MAX_RAISE,
          FAST_ACK_MAX_RAISE, eng_t.threshold_raised)

except Exception as e:
    check("Fast-ack threshold learning", False, "no error", str(e))


# TEST 6 — StorageEngine imports and initializes

print("\n" + "="*55)
print("TEST 6 — StorageEngine imports and initializes")
print("="*55)

try:
    from core.storage_engine import StorageEngine

    session_state_s = {
        "session_id": "TEST",
        "storage_free_mb": 0,
    }
    storage = StorageEngine(
        queue.Queue(maxsize=50),
        threading.Event(),
        session_state_s,
        threading.Lock()
    )
    check("StorageEngine instantiates without error", True)

    stats = storage.get_stats()
    check("get_stats() returns dict with expected keys",
          all(k in stats for k in ["events_written","clips_saved","free_mb"]),
          "all keys present", list(stats.keys()))
    check("free_mb is positive float",
          stats["free_mb"] > 0,
          "> 0", stats["free_mb"])
    print(f"     Free storage: {stats['free_mb']:.0f}MB")

except Exception as e:
    check("StorageEngine imports and initializes", False, "no error", str(e))


# TEST 7 — db_queue message dispatch (without real DB writes)
# Just for the testing purpose, we will create a StorageEngine instance and call _dispatch() with each valid action type. We will not actually write to the database, but we will verify that no exceptions are raised for valid actions.

print("\n" + "="*55)
print("TEST 7 — db_queue message types accepted by StorageEngine")
print("="*55)

valid_actions = [
    "INSERT_EVENT", "ACKNOWLEDGE_EVENT", "CHECKPOINT",
    "SAVE_CLIP", "SESSION_CLOSE", "FLAG_THRESHOLD_CHANGE",
    "GENERATE_REPORT"
]

try:
    from core.storage_engine import StorageEngine, SHUTDOWN_SENTINEL
    from core.database import create_tables, open_session
    create_tables()
    real_session_id = open_session("OP001")

    db_q_test = queue.Queue(maxsize=50)
    shut_test  = threading.Event()
    ss_test    = {"session_id": real_session_id, "storage_free_mb": 9999}
    sl_test    = threading.Lock()

    # Verify each action is handled without crash
    eng_s = StorageEngine(db_q_test, shut_test, ss_test, sl_test)

    for action in valid_actions:
        # _dispatch should not raise for any valid action
        try:
            eng_s._dispatch(action, {
                "action":     action,
                "session_id": real_session_id,
                "data":       {"type": "TEST", "session_id": real_session_id},
                "perclos":    0.0,
                "threshold":  0.0,
                "amount":     0.0,
                "operator_name": "Test",
                "generate_report": False,
            })
            check(f"Action '{action}' dispatches without crash", True)
        except Exception as e:
            check(f"Action '{action}' dispatches without crash",
                  False, "no error", str(e)[:60])

except Exception as e:
    check("StorageEngine dispatch test", False, "no error", str(e))


# SUMMARY
# Overall summary of test results

total = passed + failed
print(f"  RESULTS: {passed}/{total} tests passed")
if failed == 0:
    print("   ALL TESTS PASSED")
    print("  Alert engine and storage engine verified.")
    print("  Next: uv run scripts/generate_audio.py to create MP3 files")
else:
    print(f"   {failed} TESTS FAILED")
print("="*55)

sys.exit(0 if failed == 0 else 1)